package com.wiryadev.ghiblipedia.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF9c413e)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFffdad6)
val md_theme_light_onPrimaryContainer = Color(0xFF410004)
val md_theme_light_secondary = Color(0xFF775654)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFffdad7)
val md_theme_light_onSecondaryContainer = Color(0xFF2c1514)
val md_theme_light_tertiary = Color(0xFF735b2f)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFffdea6)
val md_theme_light_onTertiaryContainer = Color(0xFF271900)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfcfcfc)
val md_theme_light_onBackground = Color(0xFF201a1a)
val md_theme_light_surface = Color(0xFFfcfcfc)
val md_theme_light_onSurface = Color(0xFF201a1a)
val md_theme_light_surfaceVariant = Color(0xFFf4dddb)
val md_theme_light_onSurfaceVariant = Color(0xFF524342)
val md_theme_light_outline = Color(0xFF857372)
val md_theme_light_inverseOnSurface = Color(0xFFfbeeec)
val md_theme_light_inverseSurface = Color(0xFF362f2e)